/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssenzeRouteImport } from './routes/assenze'
import { Route as ClassiRouteImport } from './routes/classi'
import { Route as DocentiRouteImport } from './routes/docenti'
import { Route as ImpostazioniRouteImport } from './routes/impostazioni'
import { Route as OrarioRouteImport } from './routes/orario'
import { Route as ReportRouteImport } from './routes/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssenzeRoute = AssenzeRouteImport.update({
  id: '/assenze',
  path: '/assenze',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassiRoute = ClassiRouteImport.update({
  id: '/classi',
  path: '/classi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentiRoute = DocentiRouteImport.update({
  id: '/docenti',
  path: '/docenti',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniRoute = ImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const OrarioRoute = OrarioRouteImport.update({
  id: '/orario',
  path: '/orario',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assenze': typeof AssenzeRoute
  '/classi': typeof ClassiRoute
  '/docenti': typeof DocentiRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/orario': typeof OrarioRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assenze': typeof AssenzeRoute
  '/classi': typeof ClassiRoute
  '/docenti': typeof DocentiRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/orario': typeof OrarioRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assenze': typeof AssenzeRoute
  '/classi': typeof ClassiRoute
  '/docenti': typeof DocentiRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/orario': typeof OrarioRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assenze'
    | '/classi'
    | '/docenti'
    | '/impostazioni'
    | '/orario'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assenze'
    | '/classi'
    | '/docenti'
    | '/impostazioni'
    | '/orario'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/assenze'
    | '/classi'
    | '/docenti'
    | '/impostazioni'
    | '/orario'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssenzeRoute: typeof AssenzeRoute
  ClassiRoute: typeof ClassiRoute
  DocentiRoute: typeof DocentiRoute
  ImpostazioniRoute: typeof ImpostazioniRoute
  OrarioRoute: typeof OrarioRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assenze': {
      id: '/assenze'
      path: '/assenze'
      fullPath: '/assenze'
      preLoaderRoute: typeof AssenzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classi': {
      id: '/classi'
      path: '/classi'
      fullPath: '/classi'
      preLoaderRoute: typeof ClassiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docenti': {
      id: '/docenti'
      path: '/docenti'
      fullPath: '/docenti'
      preLoaderRoute: typeof DocentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni': {
      id: '/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof ImpostazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orario': {
      id: '/orario'
      path: '/orario'
      fullPath: '/orario'
      preLoaderRoute: typeof OrarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssenzeRoute: AssenzeRoute,
  ClassiRoute: ClassiRoute,
  DocentiRoute: DocentiRoute,
  ImpostazioniRoute: ImpostazioniRoute,
  OrarioRoute: OrarioRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
